# YUROS BASHRC PACKAGES
# copyright Al Muhdil Karim <karim@yuros.org>
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
PS1='[\u@\h \W]\$ '


# 
# Load binary from /etc/xdg/bash/library/
if test -d /etc/xdg/bash/library/; then
	for bashlib in /etc/xdg/bash/library/*.sh; do
		test -r "$bashlib" && . "$bashlib"
	done
	unset bashlib
fi


# 
# Load themes from /etc/xdg/bash/theme/
. /etc/xdg/bash/theme/default